hexa/catalog/models.py, hexa/core/management/commands/reindex_content.py, hexa/core/models/behaviors.py, hexa/pipelines/models.py, hexa/plugins/connector_airflow/models.py, hexa/plugins/connector_dhis2/models.py, hexa/plugins/connector_s3/models.py
Fixes index (and index permissions) duplicates
=> Index refactor

hexa/catalog/sync.py, hexa/plugins/connector_dhis2/api.py, hexa/plugins/connector_dhis2/models.py
Iterator instead of full result set when importing dhis2 data
=> Import large DHIS2 instances

hexa/plugins/connector_dhis2/schema.py, hexa/plugins/connector_s3/schema.py, hexa/user_management/schema.py
This PR:
- Completes the `User` type with a few fields and adds an `Avatar` type
- Refactors the `login` mutation (input and output)
- Adds a `logout` mutation
No tests ATM, will add some after the S3 PRs are merged.
=> Identity graph fine-tuning

hexa/core/graphql.py, hexa/core/test/__init__.py, hexa/core/test/graphql.py, hexa/plugins/connector_s3/models.py, hexa/plugins/connector_s3/schema.py, hexa/plugins/connector_s3/tests/test_graph.py
Just a bit of fine-tuning for the frontend
=> Allow users to explore S3 data

hexa/catalog/schema.py, hexa/plugins/connector_s3/models.py, hexa/plugins/connector_s3/schema.py, hexa/plugins/connector_s3/tests/test_graph.py
This PR provides a few small adaptations to be able to browse s3 content hierarchically.
=> HEXA-158, s3 exploration

hexa/core/templatetags/syntax.py, hexa/plugins/connector_postgresql/templates/connector_postgresql/partials/datasource_card.html, hexa/plugins/connector_s3/templates/connector_s3/partials/datasource_card.html, hexa/static/css/pygments.css, hexa/templates/partials/navbar_profile.html
=> Add pygments for syntax highlighting example snippets

.github/workflows/linting.yml, .pre-commit-config.yaml, pyproject.toml
Add:
- isort: sort imports
- autoflake: removes unused imports
- pyupgrade: upgrades old syntax and idioms 
This PR only contains the pre-commit configuration for now I'll push the code changes in another commit when we are ready to merge (otherwise the diff will be ugly)
(and we should not have other WIP branches otherwise we will have loads of conflicts)
=> Add isort, autoflake, pyupgrade

config/settings.py, hexa/core/test/test_views.py, hexa/core/urls.py, hexa/core/views.py, requirements.in, requirements.txt
Update sentry/logging config to play better with GCP
In progress: do not merge
=> HEXA-389 sentry setup

hexa/catalog/datagrids.py, hexa/comments/templates/comments/components/comment.html, hexa/core/templates/core/components/avatar.html, hexa/core/templates/core/components/quick_search/search_result.html, hexa/plugins/connector_airflow/datacards.py, hexa/plugins/connector_airflow/templates/connector_airflow/dag_run_create.html, hexa/plugins/connector_dhis2/datacards.py, hexa/plugins/connector_dhis2/datagrids.py, hexa/plugins/connector_dhis2/templates/connector_dhis2/extract_detail.html, hexa/plugins/connector_postgresql/datacards.py, hexa/plugins/connector_s3/datacards.py, hexa/plugins/connector_s3/datagrids.py, hexa/templates/partials/breadcrumbs.html, hexa/templates/user_management/partials/account_card.html, hexa/ui/datacard.py, hexa/ui/datagrid.py, hexa/ui/templates/ui/datacard/property_text.html, hexa/ui/templates/ui/datagrid/column_text.html
=> HEXA-320 Tag non-translatable strings in the HTML

hexa/plugins/connector_s3/datagrids.py, hexa/plugins/connector_s3/models.py, hexa/plugins/connector_s3/templates/connector_s3/components/action_upload.html, hexa/plugins/connector_s3/tests/test_models.py, hexa/plugins/connector_s3/views.py
- fix security flaw in views.object_uploads
- disable front/upload button if bucket RO
=> support RO buckets and directories in catalog views

CHANGELOG.md, Dockerfile, hexa/catalog/views.py, hexa/core/views.py, hexa/pipelines/views.py, hexa/plugins/connector_airflow/datacards.py, hexa/plugins/connector_airflow/last_activities.py, hexa/plugins/connector_airflow/views.py, hexa/plugins/connector_dhis2/datacards.py, hexa/plugins/connector_dhis2/views.py, hexa/plugins/connector_postgresql/datacards.py, hexa/plugins/connector_postgresql/datagrids.py, hexa/plugins/connector_postgresql/views.py, hexa/plugins/connector_s3/datacards.py, hexa/plugins/connector_s3/views.py, hexa/ui/datacard/actions.py, hexa/ui/datacard/datacard.py, hexa/ui/datacard/properties.py, hexa/ui/datagrid.py, hexa/ui/tests/test_datagrid.py, hexa/ui/utils.py, hexa/user_management/models.py, hexa/visualizations/datacards.py, hexa/visualizations/views.py, requirements.in, requirements.txt
Update Django, removed S3FS and update all our other deps as well
=> HEXA-526 Update Django

hexa/plugins/connector_airflow/datacards.py, hexa/ui/datacard/actions.py, hexa/ui/datacard/datacard.py, hexa/ui/datacard/properties.py, hexa/ui/templates/ui/datacard/action.html, hexa/ui/templates/ui/datacard/heading.html, hexa/ui/templates/ui/datacard/property_url.html, hexa/ui/tests/test_datacard.py
This PR:
- Adds "show in airflow" buttons on DAG / DAG run screens (for superuser)
- Displays a link to the DAG in the DAG run card
- Adds a few options and changes in the Datacard / Action classes to make it work
- Adds some tests
https://user-images.githubusercontent.com/690667/147492295-8f9dfc1e-e15b-4f40-9f82-4828e5a698d6.mov
=> Pipeline UX fine-tuning, round 2

docker-compose.yaml, hexa/ui/static_src/bs.config.js, hexa/ui/static_src/package-lock.json, hexa/ui/static_src/package.json, hexa/ui/static_src/tailwind.config.js
This PR:
- Enables tty for our tailwind service in docker-compose to prevent tailwind watcher from aborting
- Updates our config to make it compatible with Tailwind 3.x
=> Tailwind wach fix

hexa/plugins/connector_s3/api.py, hexa/plugins/connector_s3/models.py
This PR tries to rationalize the way we interact with S3:
- Cleaning / Harmonizing of data received from S3 moves to the API layer (ETag, Size, missing directories...)
- Harmonize vocabulary (info / object_data / metadata -> metadata)
=> (PR on PR) Attempt at simplifying S3 sync

CHANGELOG.md, hexa/plugins/connector_dhis2/sync.py, hexa/plugins/connector_dhis2/tests/test_models.py
=> Issue with DHIS2 sync / Indicator types duplicates

config/schema.py, config/settings.py, config/urls.py, docker-compose.yaml, hexa/user_management/tests/test_graph.py
- A bit of fine-tuning to our existing GraphQL setup
- Removed parts of the Graph that are not stable / usable yet
- Add tests for auth
=> Back to GraphQL

.devcontainer/devcontainer.json, .devcontainer/library-scripts/python-debian.sh, .devcontainer/scripts/postCreateCommand.sh
* Add black to devcontainer
* Add pre-commit to devcontainer
=> Devcontainer fixes

hexa/plugins/connector_dhis2/api.py, hexa/plugins/connector_dhis2/tests/test_api.py
If locale is none, fallback on english locale and not the first one available. If no english locale, use field value
=> HEXA-555 Fix DHIS2 demo

docker-entrypoint.sh, hexa/plugins/connector_accessmod/schema.py, hexa/plugins/connector_accessmod/tests/test_file_graph.py
=> Fix AM download URLs

config/settings.py
Needed for the tracing of sentry in Accessmod
=> CORS: Accept 'sentry-trace' header

hexa/catalog/urls.py, hexa/core/urls.py, hexa/metrics/urls.py, hexa/plugins/connector_accessmod/tests/test_analysis_graph.py, hexa/plugins/connector_accessmod/urls.py, hexa/plugins/connector_airflow/urls.py, hexa/plugins/connector_dhis2/urls.py, hexa/plugins/connector_postgresql/urls.py, hexa/plugins/connector_s3/urls.py, hexa/user_management/tests/test_views.py, hexa/user_management/urls.py, hexa/visualizations/urls.py
This is needed to make the proxy made y the new frontend work
=> Add trailing slash to all urls

hexa/user_management/graphql/schema.graphql, hexa/user_management/schema.py, hexa/user_management/tests/test_graph.py, hexa/user_management/tests/test_schema.py
I'm not sure yet how to manage the second step which is to use the token received in the mail to set a new password. Django handles that nicely by putting the token in a cookie instead of the url when it returns the page.
=> AC-42: User should be able to reset their password

hexa/core/context_processors.py, hexa/core/urls.py, hexa/core/views.py, hexa/templates/partials/breadcrumbs.html
The collections' pages are served by the new frontend (openhexa-frontend)
=> HEXA-612: Implement Data collections prototype

hexa/plugins/connector_accessmod/graphql/schema.graphql, hexa/plugins/connector_accessmod/models.py, hexa/plugins/connector_accessmod/tests/schema/test_analysis.py, hexa/user_management/graphql/schema.graphql, hexa/user_management/tests/test_schema.py
Just a few minor changes to the graph, and most of all, re-activate analysis tests in graph
=> Authors, owners, and unskip some tests

hexa/plugins/connector_accessmod/queue.py
* Accept `MultiPoint` geometries for health facilities
* Accept `Polygon` geometries for water bodies
* Generate geojson after status update
=> Fix and speed up validation rules

hexa/plugins/connector_accessmod/migrations/0047_zonalstatisticsanalysis.py
Migration contains a wrong data import, deployed on both demo and production. But for the sake of correctness, let's fix it
=> Migration history is wrong, might help future deployment

hexa/plugins/connector_s3/models.py, hexa/plugins/connector_s3/urls.py, hexa/plugins/connector_s3/views.py
I just removed a '/' to avoid having two in the link.
=> S3 links with '//'

config/urls.py, hexa/user_management/tests/test_views.py
who will redirect us back to our login page ounce his job is done
=> After logout, redirect to JupyterHub's logout page 

hexa/core/credentials.py, hexa/notebooks/credentials.py, hexa/pipelines/credentials.py, hexa/plugins/connector_s3/api.py, hexa/plugins/connector_s3/credentials.py, hexa/plugins/connector_s3/tests/test_api.py, hexa/plugins/connector_s3/tests/test_credentials.py
Preliminary work to support fuse mounts inside pipeline environment
Also: increase delay before IAM.assumeRole, should fix the "first dag run always crash"
=> Refactor s3 credentials, inject fuse config into pipeline env vars

hexa/catalog/datagrids.py, hexa/plugins/connector_dhis2/templates/connector_dhis2/extract_detail.html, hexa/ui/datagrid.py, hexa/ui/templates/ui/datagrid/column_boolean.html, hexa/ui/templates/ui/datagrid/column_date.html, hexa/ui/templates/ui/datagrid/column_duration.html, hexa/ui/templates/ui/datagrid/column_leading.html, hexa/ui/templates/ui/datagrid/column_link.html, hexa/ui/templates/ui/datagrid/column_status.html, hexa/ui/templates/ui/datagrid/column_tag.html, hexa/ui/templates/ui/datagrid/column_text.html, hexa/ui/templates/ui/datagrid/datagrid.html, hexa/ui/templates/ui/tag.html
I can also split this PR in two (one for the fix and one for the improvement) if you want prefer
=> Fix datagrid width

hexa/plugins/connector_accessmod/models.py
=> fix(Accessmod): Transport Network may be null

.github/pull_request_template.md
See https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
=> Experimenting with PR templates

hexa/plugins/connector_airflow/admin.py, hexa/plugins/connector_airflow/tests/test_sync.py
Add a button in openhexa admin to sync the airflow cluster
=> Action for airflow cluster sync in openhexa admin

hexa/plugins/connector_airflow/models.py, hexa/plugins/connector_airflow/schema.py, hexa/plugins/connector_airflow/tests/schema/test_dag.py
Add sort by and label and dag_id  on pipelines.
- Change 1
- Change 2
=> feat(Pipelines): sort pipelines by label and id

hexa/plugins/connector_gcs/credentials.py
Quick fix i forgot to merge a while ago
=> Fix GCS buckets access from pipelines

hexa/pipelines/management/commands/pipelines_runner.py
Fix wrong container name in app armor notation in the pipeline-v2 runner
=> Fix wrong apparmor annotation in pipeline runner

hexa/pipelines/management/commands/pipelines_runner.py
- Add toleration/affinity in pipeline runner
- Remove microsecond/tzinfo from execution time to have simpler pod name
=> Simplify execution time, add tolerations/affinity in pipeline-v2 runner

hexa/pipelines/authentication.py
Fix better mock for has_feature_flag() on PipelineRunUser
=> Fix better mock for has_feature_flag() on PipelineRunUser for pipelines-v2

hexa/pipelines/templates/pipelines/status.html
Update status page with color and max-width
=> Update pipelines-v2 status page with color and max-width

hexa/catalog/graphql/schema.graphql, hexa/core/graphql/schema.graphql, hexa/data_collections/graphql/schema.graphql, hexa/notebooks/graphql/schema.graphql, hexa/pipelines/graphql/schema.graphql, hexa/user_management/graphql/schema.graphql, hexa/user_management/schema.py, hexa/visualizations/graphql/schema.graphql, hexa/workspaces/graphql/schema.graphql
=> fix(2FA): Do not return the user if 2FA is enabled but not verified

hexa/workspaces/schema.py
OPENHEXA-KZ
- Change 1
- Change 2
=> fix(workspaces): only authenticated user can create workspace

hexa/workspaces/schema/types.py
=> Fix permission error for workspace

hexa/pipelines/graphql/schema.graphql, hexa/plugins/connector_accessmod/graphql/schema.graphql, hexa/plugins/connector_airflow/graphql/schema.graphql, hexa/user_management/graphql/schema.graphql
Require login for some mutations when needed see [task](https://github.com/orgs/BLSQ/projects/4/views/2?pane=issue&itemId=19895043)  .
- Add  @LoginRequired annotation on schemas
=> feat: require login on mutations

.pre-commit-config.yaml
=> Update isort to comply with pre-commit action update

hexa/databases/api.py, hexa/databases/graphql/schema.graphql, hexa/databases/schema.py, hexa/databases/tests/test_api.py, hexa/databases/tests/test_schema.py, hexa/databases/tests/test_utils.py, hexa/workspaces/models.py
Allow a workspace admin to change the workspace database by generating a new one.
- Increase default password length to 16
- Add api for updating a database role password.
- Create mutation for generating a new password given a workspace
=> feat(Workspaces): change workspace database password

hexa/databases/graphql/schema.graphql, hexa/databases/schema.py, hexa/databases/tests/test_schema.py
Rename mutation and types for database password genetation
=> chore(Workspaces): rename mutation and types for database password

hexa/workspaces/tests/test_views.py, hexa/workspaces/views.py
Inject workspace database credentials (name, host, port...) into workspace notebooks
=> feat(Workspaces): inject database credentials into workspace notebooks

hexa/files/permissions.py
Only admins & editors can delete/create objects; all members can download
=> Fix workspaces files permissions

hexa/workspaces/models.py
Like the title says - nothing special
=> Add a proper default description for workspaces

.github/workflows/build_docker_image.yml, .github/workflows/lint.yml, .github/workflows/test.yml
=> chore: Update github actions workflows

hexa/workspaces/schema/mutations.py, hexa/workspaces/tests/test_schema/test_workspace.py
=> fix(Workspaces): Link in invites is invalid

hexa/workspaces/models.py, hexa/workspaces/tests/test_views.py, hexa/workspaces/views.py
Add database URI connection string
=> fix(Connections):add database URI connection string

hexa/workspaces/admin.py, hexa/workspaces/models.py
Connection admin fine-tuning.
- Add connection type on connection list.
- Add  id, connection on connectionField list.
- Add inline for fields in connection form.
Connection list
Connection form
ConnectionField list
=> feat(Connections): connection admin fine-tuning

hexa/pipelines/management/commands/pipelines_runner.py, hexa/workspaces/permissions.py
=> Fix container length

hexa/workspaces/graphql/schema.graphql, hexa/workspaces/schema/types.py
Add a permission on the workspace to let the user know if is can access the notebooks component
=> fix(Notebooks): Add a launchNotebooks permissions

hexa/databases/graphql/schema.graphql, hexa/databases/schema.py, hexa/databases/tests/test_schema.py, hexa/databases/utils.py
=> feat(Database): Display all tables' rows and let the user select the order by

hexa/pipelines/templates/pipelines/mails/run_report.html, hexa/pipelines/tests/test_schema.py, hexa/pipelines/utils.py
Adaptations of the emails sent after a run
=> fix(Pipelines): Improve mail notifications text

hexa/workspaces/templates/workspaces/mails/invite_external_user.html, hexa/workspaces/templates/workspaces/mails/invite_external_user.txt, hexa/workspaces/templates/workspaces/mails/invite_member.html
Reformat mail content for invitations
- Add lines break
- Text changes
=> chore(Workspaces): improve invitations mails

hexa/databases/tests/test_schema.py, hexa/workspaces/models.py, hexa/workspaces/tests/test_views.py
Use proxy for WORKSPACE_DATABASE_URL.
- Change 1
- Change 2
=> chore(Workspaces): use proxy for db_url

hexa/workspaces/models.py
=> Connections UX improvements

.github/workflows/release-please.yml
Configure release-please to work like in the openhexa-frontend repo
=> chore: Configure release-please

hexa/pipelines/graphql/schema.graphql, hexa/pipelines/schema.py, hexa/pipelines/tests/test_schema.py
Add permission to check if a  pipeline can be scheduled or not.
- Add schedule permission
=> chore(Pipelines): add schedule permission

hexa/workspaces/admin.py
Setup workspace invitations on django admin view.
- Register WorkspaceInvitation to django admin. 
=> feat(Workspaces): add workspace invitations list to django admin

hexa/workspaces/schema/mutations.py, hexa/workspaces/tests/test_schema/test_workspace.py
Automatically log in users after signup.
- authenticate and login user.
[Screencast from 07-20-2023 10:34:05 AM.webm](https://github.com/BLSQ/openhexa-app/assets/25453621/dae17686-fc42-4c91-aab9-ca84635639e1)
=> feat(Workspaces): Automatically log in users after signup

hexa/pipelines/schema.py
Sometimes the table or bucket object that was stored as output of a pipeline run has been deleted. Let's not include it in the outputs then.
- Run a pipeline that creates a output.
- Delete this output from jupyter
- Try to open the page of the run
=> fix(Pipelines): Do not throw an error when an output does not exist anymore

hexa/workspaces/schema/mutations.py, hexa/workspaces/tests/test_schema/test_workspace_connection.py
Fix relative to [issue](https://github.com/BLSQ/openhexa-team/issues/534) about connection that get created when one of his field is invalid.
- Wrap connection creation logic into atomic transaction.
- Add test
Try to add a connection with an invalid field name, the connection should be not created.
=> fix(Connections): abort connection creation if an error occurs

hexa/datasets/models.py, hexa/datasets/schema/mutations.py, hexa/datasets/schema/types.py, hexa/datasets/tests/test_models.py
User can easily get a file by its filename
=> fix(datasets): Fix get_file_by_name for a version

hexa/pipelines/models.py, hexa/pipelines/schema.py, hexa/pipelines/tests/test_schema.py
Relative to [issue](https://github.com/BLSQ/openhexa-team/issues/539) :  allow scheduling for pipelines if all parameters have default value.
- Add  check on pipeline parameters default value
=> feat(Pipelines): allow scheduling if all params have default value

hexa/datasets/models.py, hexa/datasets/permissions.py, hexa/datasets/schema/mutations.py, hexa/datasets/schema/types.py, hexa/datasets/tests/test_models.py, hexa/workspaces/models.py
This is a hack as we will revamp the way we manage the permissions of the users and pipeline' runs.
=> Fix datasets permissions management to be able to use them in the pipelines

hexa/workspaces/models.py
For backwards-compatibility purposes
=> Fix(Connections): add _API_URL env variable for Iaso connections

hexa/pipelines/graphql/schema.graphql, hexa/pipelines/tests/test_schema.py
=> fix(Pipelines): add timeout to PipelineRun schema

hexa/workspaces/tests/test_views.py
Add tests for workspace connections env variables.
=> chore(Workspaces): add tests for connections env variables

hexa/pipelines/models.py, hexa/pipelines/tests/test_schema.py
Relative to issue (https://github.com/BLSQ/openhexa-team/issues/573). This PR improves pipelines with parameters scheduling by adding more flexibility on the way we allow/disallow scheduling.
- Allow pipelines to be scheduled when all parameters are not required 
- Prevent scheduling of pipelines with required params without default value.
=> fix(Pipelines): allow scheduling of pipelines

README.md
It wasn't explained how you work with the pipelines locally in the local development section.
see BLSQ/openhexa-team#565
=> Explain how to develop locally the pipelines

Dockerfile
Fix errors on static files manifest not generated.
=> fix(Core): collecstatic files

.github/workflows/release-please.yml
Let's bump minor versions on feat: commits.
=> chore: release please bump policy change

hexa/pipelines/management/commands/pipelines_runner.py
Goal: make pipeline logs more useful.
- Add info about spawner and Docker images in pipeline logs
- Don't use the env vars dict to "carry" the Docker image information to runner functions
- A series of cosmetic changes (better names, typo fixes...)
Run a pipeline :)
=> feat: better logging for pipelines

hexa/plugins/connector_dhis2/datacards.py, hexa/plugins/connector_postgresql/datacards.py, hexa/plugins/connector_s3/templates/connector_s3/bucket_detail.html
It doesn't make sense to keep those as we have removed the metadata already.
=> chore: remove catalog sync buttons

hexa/pipelines/tests/test_views.py, hexa/pipelines/views.py
The type of parameter used to convert string values to a real bool was not correct
=> fix(Pipelines): Fix boolean -> bool for the pipeline webhook

CHANGELOG.md, README.md, config/settings.py, config/urls.py, hexa/catalog/datacards.py, hexa/core/templatetags/colors.py, hexa/files/static/README.MD, hexa/pipelines/templates/pipelines/mails/run_report.html, hexa/pipelines/templates/pipelines/mails/run_report.txt, hexa/plugins/connector_airflow/datacards.py, hexa/plugins/connector_dhis2/api.py, hexa/plugins/connector_dhis2/datacards.py, hexa/plugins/connector_postgresql/datacards.py, hexa/plugins/connector_s3/api.py, hexa/plugins/connector_s3/datacards.py, hexa/templates/layouts/base.html, hexa/templates/partials/navbar.html, hexa/user_management/admin.py, hexa/user_management/backends.py, hexa/user_management/templates/user_management/account_creation_email.html, hexa/user_management/templates/user_management/account_creation_subject.txt, hexa/user_management/templates/user_management/token.txt, hexa/workspaces/migrations/0037_alter_workspacemembership_access_token_and_more.py, hexa/workspaces/models.py, hexa/workspaces/templates/workspaces/mails/invite_external_user.html, hexa/workspaces/templates/workspaces/mails/invite_external_user.txt, hexa/workspaces/templates/workspaces/mails/invite_member.html, hexa/workspaces/templates/workspaces/mails/invite_member.txt, hexa/workspaces/tests/test_schema/test_workspace.py, hexa/workspaces/utils.py
=> Rename OpenHexa to OpenHEXA

hexa/core/context_processors.py
=> core: remove dashboard entry

hexa/pipelines/tests/test_schema.py
=> fix(Pipelines): fix tests

hexa/pipelines/schema.py, hexa/pipelines/tests/test_schema.py
Use correct exception when calling get_bucket_object.
- Change import module.
=> fix(PipelineRun): change NotFound  import module

hexa/pipelines/graphql/schema.graphql, hexa/pipelines/models.py, hexa/pipelines/permissions.py, hexa/pipelines/schema/__init__.py, hexa/pipelines/schema/mutations.py, hexa/pipelines/schema/queries.py, hexa/pipelines/schema/types.py, hexa/pipelines/tests/test_schema.py, hexa/pipelines/tests/test_schema/test_pipeline_versions.py, hexa/pipelines/tests/test_schema/test_pipelines.py
I need this for the frontend to display easily the badge on the latest version. In the future this will become the isActiveVersion when users will be able to select a different version as the active one.
=> Add isLatestVersion on PipelineVersion

hexa/pipelines/schema/queries.py
Fix typo on pipeline_version  query resolver.
=> fix(Pipelines): typo on permission module

hexa/pipelines/graphql/schema.graphql, hexa/pipelines/models.py, hexa/pipelines/permissions.py, hexa/pipelines/schema/mutations.py, hexa/pipelines/schema/types.py, hexa/pipelines/tests/test_schema/test_pipeline_versions.py, hexa/pipelines/tests/test_schema/test_pipelines.py
I also fixed a bug where every users were able to create pipeline versions (there were no check on the membership)
=> feature(pipelines): Add permissions on PipelineVersion; users can update versions

hexa/databases/tests/test_utils.py, hexa/databases/utils.py, hexa/workspaces/graphql/schema.graphql, hexa/workspaces/permissions.py, hexa/workspaces/schema/mutations.py, hexa/workspaces/schema/types.py, hexa/workspaces/tests/test_schema/test_workspace.py
Allow user (admin, editor) to delete a table from the workspace database.
- Add delete_table in databases module
- Add a new mutation in workspace module
=> feat(Workspaces): delete workspace database table

README.md, docker-compose.yaml
Add a profile to also run a specific image of the frontend.
=> chore(dev): Add a frontend profile to run the frontend from the app repo

config/settings/base.py, docker-compose.yaml, hexa/pipelines/management/commands/pipelines_runner.py, hexa/workspaces/graphql/schema.graphql, hexa/workspaces/models.py, hexa/workspaces/schema/mutations.py, hexa/workspaces/tests/test_schema/test_workspace.py, hexa/workspaces/views.py
This PR intends to allow users to edit the docker image used to run pipelines and jupyterlab for  the workspace.
=> feat(Workspaces): allow user to update workspace image  and rename PIPELINE_IMAGE env

hexa/workspaces/permissions.py, hexa/workspaces/tests/test_models.py, hexa/workspaces/tests/test_schema/test_workspace_connection.py
See https://bluesquare.atlassian.net/jira/software/c/projects/HEXA/boards/330?assignee=712020%3A1d0055ff-af59-47b7-b48d-4d37e2a0d0b9&selectedIssue=HEXA-964
=> feat(Connections): editor can create/update/delete connection

docker-compose.yaml, docker-entrypoint.sh
Change the DB port exposed on the dev machine to 5434
=> chore: Update database port in docker-compose.yaml

hexa/databases/graphql/schema.graphql, hexa/datasets/graphql/schema.graphql, hexa/files/graphql/schema.graphql, hexa/pipelines/graphql/schema.graphql, hexa/tags/graphql/schema.graphql, hexa/user_management/graphql/schema.graphql, hexa/workspaces/graphql/schema.graphql
Documenting everything
#HEXA-935
=> As a api user i d like the graph ql api to be documented

hexa/datasets/api.py, hexa/datasets/graphql/schema.graphql, hexa/datasets/schema/mutations.py, hexa/datasets/schema/types.py, hexa/datasets/tests/test_schema.py, hexa/files/basefs.py, hexa/files/gcp.py, hexa/files/s3.py, hexa/files/tests/mocks/bucket.py, hexa/files/tests/test_api.py
move generation of file uploadUrl to a separate mutation
deprecate uploadUrl in DatasetVersionFile
=> feat(Dataset): generate upload url independetly

hexa/pipelines/signals.py, requirements.txt
Allows users to call pipeline web hooks from a browser app
=> Cors pipelines webhook

.env.dist, .github/workflows/build_docker_image.yml, .github/workflows/test.yml, Dockerfile, config/settings/base.py, config/settings/test.py, docker-compose.yaml
Those changes:
- make sure the build args are set up even when we run `docker build`
- handle passed env vars to set the right ones for Django
this is linked to https://github.com/BLSQ/openhexa/pull/44
=> Handle settings when using proxy/load balancer or containerized

config/schema.py, hexa/core/graphql/schema.graphql, hexa/core/schema.py, hexa/core/tests/test_schema.py
Add a query to return django password requirements.
=> feat(Core): add query to return password requirements

hexa/workspaces/models.py
=> fix(GCP): Bucket cannot contain '.' or be a recognized top-level domain

hexa/datasets/schema/types.py
Typo in the name of the property to get the content type from
=> fix(datasets): fix the backward compatibility field 'uploadUrl' on CreateDatasetVersionFileResult

config/settings/base.py, hexa/files/backends/fs.py, hexa/files/tests/backends/test_fs.py
=> fix(CORS): Include the files/up & files/dl to the cors exempted urls

hexa/datasets/graphql/schema.graphql, hexa/datasets/models.py
Implemented to match the specs of the mockups of Mariano
=> chore(datasets): Add a property on DatasetVersionFile to get the size of an file

hexa/datasets/models.py, hexa/datasets/tests/test_generate_sample.py
=> fix(jsonfield): Override encode() to remove NaN values

config/settings/base.py, hexa/core/middlewares.py
We have already updated our ingress to forward the user ip. This is going to be used to provide more data to our analytics endpoint.
=> chore(IP): Set REMOTE_ADDR from the X-Forwarded-For header if present

hexa/datasets/queue.py
- Adds the number of rows without nan per column
- skips any byte column for profiling
=> Fix remove byte profiling

hexa/datasets/queue.py
I don't understand how it was possible to run the tests with xlsx files without the engine ?
=> fix(datasets): Set the correct engine for xls files & do not crash when DatasetVersionFile do not exist anymore

hexa/pipelines/management/commands/pipelines_runner.py, hexa/pipelines/tests/test_pipelines_runner.py
=> HEXA-1111 stringify env var

hexa/pipelines/management/commands/pipelines_runner.py
Adds comment to mark that env var need to be stringified
=> fix(pipeline): comment env var requirement

docker-compose.yaml
Instead of trying to compile polars to run in a emulated amd64 on arm64, let's try first to run the app in a non emulated env.
=> chore: Build images for the dev's arch

hexa/pipeline_templates/models.py, hexa/pipelines/schema/mutations.py
=> chore: Change upgrade() to upgrade_pipeline() to be more explicit and add docstrings on a few PipelineTemplate methods

hexa/pipeline_templates/schema/mutations.py, hexa/pipelines/models.py, hexa/pipelines/tests/test_models.py, hexa/pipelines/tests/test_schema/test_pipelines.py
Improve the tracking analytics as per the details shared by Mariano
=> feat: instrument and improve feature adoption analytics (HEXA-1156)

hexa/workspaces/graphql/schema.graphql, hexa/workspaces/schema/types.py, hexa/workspaces/tests/test_schema/test_dhis2_connection.py
gathers name and level under label graphql field
=> feat(Connection): HEXA-1136 moves name to label

README.md, hexa/workspaces/graphql/schema.graphql, hexa/workspaces/schema/types.py
A bunch of small changes to improve the code quality
=> Small tweaks for the DSHI2 integration

backend/hexa/core/templatetags/static_with_domain.py
removes double slash in email invitation image url
=> fix double slash

frontend/next-env.d.ts, frontend/src/workspaces/features/RunPipelineDialog/DHIS2Widget.tsx
Adds cache to fix selected items disappearing
(Dont take opaque dialog into account, thats another lib update) 
https://github.com/user-attachments/assets/1222dc2a-2f1c-4156-a14f-f410a74ca1d4
=> HEXA-1243 fix(dhis2): keep selected ids and labels from previous query

frontend/package.json, frontend/src/core/components/DataCard/MarkdownProperty.tsx, frontend/src/core/components/MarkdownEditor/MarkdownEditor.module.css, frontend/src/core/components/MarkdownEditor/MarkdownEditor.tsx, frontend/src/datasets/features/UploadDatasetVersionDialog/UploadDatasetVersionDialog.tsx, frontend/src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug]/index.tsx, frontend/src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx, frontend/src/pipelines/features/PublishPipelineDialog/PublishPipelineDialog.test.tsx
Adds makrdown to dataset description
https://github.com/user-attachments/assets/2985c7ae-bd8a-454c-b460-324391943c8e
=> feat(dataset): add markdown editor to dataset (HEXA-1204) 

backend/Dockerfile
Used by the local hosting solution when mounting the data volume
=> fix: Set uid & gid to 1000 by default

frontend/codegen.yml, frontend/schema.generated.graphql
We need an aggregated file for https://the-guild.dev/graphql/inspector/docs/products/action since glob are not working for this github action https://github.com/graphql-hive/graphql-inspector/issues/1978
=> chore: generate aggregated graphql file (HEXA-1238)

frontend/src/core/features/SpotlightSearch/HighlightedLink.tsx, frontend/src/core/features/SpotlightSearch/useHighlightRow.tsx
Simplify showing the truncated name and the full name
=> fix: search bar flickering on scroll due to on hover styles (HEXA-1267)

backend/hexa/files/backends/fs.py, backend/hexa/files/backends/gcp.py, backend/hexa/files/tests/backends/test_fs.py, backend/hexa/files/tests/backends/test_gcp.py
Files in hidden directories were not ignored
=> fix: ignore hidden files 

backend/hexa/workspaces/templates/workspaces/mails/invite_new_user.mjml
Removed promotional content from email template
https://bluesquare.atlassian.net/browse/HEXA-1245
=> feat: removed promotion content from email template

backend/hexa/workspaces/templates/workspaces/mails/add_existing_user.mjml, backend/hexa/workspaces/templates/workspaces/mails/add_existing_user.txt, backend/hexa/workspaces/templates/workspaces/mails/invite_new_user.mjml, backend/hexa/workspaces/templates/workspaces/mails/invite_new_user.txt, backend/hexa/workspaces/utils.py
- removes context from txt file
- removes content from existing email user
- removes attachments
=> Hexa 1245 feat cleaner email invitation for existing

backend/hexa/pipelines/management/commands/pipelines_runner.py, backend/hexa/pipelines/tests/test_pipelines_runner.py
=> fix: exposes pipeline code in kubernetes

frontend/src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug]/from/[sourceWorkspaceSlug]/access.tsx
Workspace specific Access revoke and sharing is not available for the dataset as it is shared at the Org level
=> fix: Inconsistent behavior when dataset is published at the org level (PATHWAYS-888)

frontend/public/locales/en/messages.json, frontend/public/locales/fr/messages.json, frontend/src/organizations/features/OrganizationMembers/AddOrganizationMemberDialog/AddOrganizationMemberDialog.tsx, frontend/src/organizations/features/OrganizationMembers/UpdateOrganizationMemberDialog/UpdateOrganizationMemberDialog.tsx, frontend/src/organizations/layouts/Sidebar/NavItem.tsx, frontend/src/organizations/layouts/Sidebar/OrganizationsSidebar.tsx, frontend/src/workspaces/features/BucketObjectPicker/BucketObjectPicker.tsx
Minor cosmetic improvements : 
- Reworks the Nav item for organization to avoid truncation
- Add a toast on succeeded organization invitation
=> fix: truncation of organization names and toast on success invitation (PATHWAYS-882)

backend/hexa/user_management/templates/user_management/mails/invite_organization.mjml, backend/hexa/user_management/templates/user_management/mails/invite_organization.txt
Truncate the list of workspace in the email
=> fix: too many workspaces in the invite for admin owners (PATHWAYS-940)

backend/hexa/user_management/graphql/schema.graphql, backend/hexa/user_management/schema.py, frontend/public/locales/en/messages.json, frontend/public/locales/fr/messages.json, frontend/schema.generated.graphql, frontend/src/graphql/types.ts, frontend/src/organizations/features/OrganizationMembers/OrganizationMembers.generated.tsx, frontend/src/organizations/features/OrganizationMembers/OrganizationMembers.graphql, frontend/src/organizations/features/OrganizationMembers/OrganizationMembers.tsx, frontend/src/organizations/features/OrganizationMembers/__tests__/OrganizationMembers.test.tsx, frontend/src/organizations/features/OrganizationMembers/__tests__/__snapshots__/OrganizationMembers.test.tsx.snap
Allow filtering memebers by role 
- Change resolver and GraphQL schema to support the role filter
- UI with dropdown
=> feat:  filter member by role (PATHWAYS-882)

frontend/src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug]/from/[sourceWorkspaceSlug]/index.tsx
fixes issue when changelog was not update on version chagne 
https://github.com/user-attachments/assets/ac17a3c9-4a8d-46ac-96b8-53d97fbc94ca
=> fix: update dataset version changelog when switching versions

backend/hexa/workspaces/models.py
Super user should have access to all workspaces
=> fix: superuser permission when not org admin/owner (HEXA-1383)
