hexa/core/templates/core/partials/dashboard_activity.html, hexa/core/templates/core/partials/dashboard_overview.html, hexa/core/views.py
The notebook count is taken from the S3 objects accessible to the user, filtered by extension.
The recent activity always shows a login for the current user and a datasource sync, always on the current day
=> Show real data on the home dashboard

README.md, config/settings.py, hexa/catalog/management/commands/sync_datasources_worker.py, hexa/catalog/models.py, hexa/catalog/queue.py, hexa/catalog/tests/test_sync.py, hexa/catalog/urls.py, hexa/catalog/views.py, hexa/plugins/connector_dhis2/datacards.py, hexa/plugins/connector_dhis2/models.py, hexa/plugins/connector_dhis2/urls.py, hexa/plugins/connector_dhis2/views.py, hexa/plugins/connector_postgresql/datacards.py, hexa/plugins/connector_postgresql/models.py, hexa/plugins/connector_postgresql/urls.py, hexa/plugins/connector_postgresql/views.py, hexa/plugins/connector_s3/datacards.py, hexa/plugins/connector_s3/models.py, hexa/plugins/connector_s3/urls.py, hexa/plugins/connector_s3/views.py, requirements.in, requirements.txt
This PR enables openhexa to delay ```sync()``` for all catalogs, and do the work in a separate process (called ```sync_datasources_worker```). This change of behavior is activated with a new settings, ```DATASOURCE_ASYNC_REFRESH```, which is False by default (no change of behavior, no change of deploy settings needed). It use the django-postgres-queue because it doesnt need a lot of new infrastructure (like celery or something else) and is suffisant for the immediate future.
Notes:
- add a new test, which set the ASYNC_REFRESH to both values to see if queued sync or immediate sync works. use package "mock" to check when datasource.sync() is called
- test pass localy, but not on GH because of dockerhub credentials, sorry :/
- it needs a new worker to run the postgresql task queue, but not …
=> Enable async datasource refresh for all catalogs

config/settings.py, hexa/core/test/runner.py
This PR enables Whitenoise caching / cache busting/
See https://whitenoise.evans.io/en/stable/django.html#add-compression-and-caching-support and https://docs.djangoproject.com/en/3.2/ref/contrib/staticfiles/#manifeststaticfilesstorage.
In a nutshell:
- `collectstatic` will generate static files with a unique hash
- using the `static` template tag will generate a link to the file names with hashes
=> Cache busting for js

hexa/plugins/connector_postgresql/models.py
By default we use the query planner statistics to determine que number of row from a table.
This can pose problems when row have been added since the last VACCUUM.
To mitigate this, if the query planner thinks a table has <10k rows, we use COUNT(*) to get an exact number.
This is a nice tradeoff between having to do full scan on huge tables vs having plain wrong counts on small tables
=> Use a better approximation for Postgres row count

hexa/pipelines/templates/pipelines/index.html, hexa/plugins/connector_airflow/datacards.py, hexa/plugins/connector_airflow/templates/connector_airflow/cluster_detail.html, hexa/plugins/connector_airflow/templates/connector_airflow/dag_detail.html, hexa/plugins/connector_airflow/templates/connector_airflow/dag_run_detail.html, hexa/plugins/connector_airflow/tests/test_views.py, hexa/plugins/connector_airflow/urls.py, hexa/plugins/connector_airflow/views.py, hexa/ui/templates/ui/dynamic/autorefresh.html
The initial goal of the PR was to auto-refresh the DAG run detail screen.
We already had some auto-refresh parts, but the implementation was linked to the section component and could not be used as-is for the cluster card.
This PR moves auto-refresh behaviour in its own independent component.
It also adds a bunch of tests for airflow screens.
=> Generic auto-refresh component

hexa/plugins/connector_dhis2/sync.py, hexa/plugins/connector_dhis2/tests/test_models.py
The PDSS and SNIS pyramids contain 24k org unit with the same id. when openhexa sync SNIS, it updates PDSS pyramid with SNIS data...
=> Duplicate dhis2 elements with the same id of different instance

hexa/plugins/connector_s3/api.py, hexa/plugins/connector_s3/tests/test_sync.py
`dir3/dir4/fileC` and `dir3/dir4` are created, but not `dir3`
=> Issue with nested-pseudo dirs

CHANGELOG.md, hexa/plugins/connector_dhis2/models.py, hexa/plugins/connector_dhis2/tests/test_models.py
DHIS2 last_synced_at should be set on instance before syncing their content, otherwise their index will keep the previous last_synced_at value
=> Fix last_synced_ad on DHIS2 content

hexa/plugins/connector_s3/credentials.py, hexa/plugins/connector_s3/models.py, hexa/plugins/connector_s3/tests/test_credentials.py, hexa/plugins/connector_s3/tests/test_models.py
This PR fixes a bad query that was causing conflicts within bucket permissions - especially when generating notebook credentials.
=> Fix for permission conflicts in S3 bucket

hexa/plugins/connector_accessmod/graphql/schema.graphql, hexa/plugins/connector_accessmod/models.py, hexa/plugins/connector_accessmod/permissions.py, hexa/plugins/connector_accessmod/schema.py, hexa/plugins/connector_accessmod/tests/schema/test_project.py
This PR drastically simplifies project permissions - this is temporary.
With this approach :
- We only have one project owner at a time
- Create a new owner permission will replace the previous one
=> Simplify project permissions

hexa/plugins/connector_accessmod/queue.py
Fix [AC-265](https://bluesquare.atlassian.net/browse/AC-265)
Geometries in the AccessMod tutorial are actually of type `MultiLineString` instead of `LineString`, this should not cause any issue in the data pipelines
=> AC-265 Fix invalid geometries wrongly detected

CHANGELOG.md, hexa/plugins/connector_accessmod/graphql/schema.graphql, hexa/plugins/connector_accessmod/schema.py, hexa/plugins/connector_accessmod/tests/schema/test_project.py
=> Accessmod project creation mutation changes

hexa/plugins/connector_s3/api.py, hexa/plugins/connector_s3/views.py
- We don't want to handle ACL in OpenHexa, as we are not handling them in s3fs/fuse.
- policy to use (need to update infra/terraform):
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Principal": "*",
"Action": "s3:GetObject",
"Resource": "arn:aws:s3:::minihexa-test1-pub/*"
}
]
}
```
=> Fix S3 public bucket

hexa/core/datagrids.py, hexa/ui/datagrid.py
I'm not really confortable with the default width of the `LinkColumn` but it's better to limit the size of this cell to leave more room for the other as all the cells without explicit width receives an equal width.
=> Improve datagrid width

hexa/plugins/connector_s3/api.py, hexa/plugins/connector_s3/tests/test_api.py, hexa/plugins/connector_s3/tests/test_credentials.py
The idea behind the PR is to be much more explicit regarding the actions that can be performed in notebooks and pipelines.
This is mostly for safety reasons (prevent unwanted operations such as a bucket deletion).
=> Restrict allowed S3 actions in S3 policy generation

hexa/app.py, hexa/data_collections/graphql/schema.graphql, hexa/data_collections/schema.py, hexa/plugins/connector_accessmod/apps.py, hexa/plugins/connector_accessmod/graphql/schema.graphql, hexa/plugins/connector_accessmod/schema.py, hexa/plugins/connector_accessmod/tests/schema/test_project.py, hexa/user_management/graphql/schema.graphql, hexa/user_management/schema.py, hexa/user_management/tests/test_schema.py
This pull request refactors the permissions model exposed in the graphql.
`authorizedActions` is renamed to `permissions` and the new data structure is a type and not an enum anymore.
⚠️ This PR is not mergeable as-is. The changes made on `AccessmodProject.permissions` will break AccessMod.
=> Permissions Refactoring

README.md
Now that we have a global OpenHexa repo, let's link to it.
- Added link in README
=> Add link to main OpenHexa repository

hexa/plugins/connector_airflow/api.py, hexa/plugins/connector_airflow/management/commands/dag_scheduler.py, hexa/plugins/connector_airflow/models.py, hexa/plugins/connector_airflow/tests/test_models.py, requirements.in, requirements.txt
This PR add a background worker in the connector_airflow, which will trigger the start of a dag based on the schedule set by an openhexa admin. Previously, the schedule was forwarded by the sync to airflow, and airflow started a DAG based on its own rules. Unfortunately, this method was challenging from an architectural point of view because it means a DagRun can be 2 types: manual and scheduled. Now, every run are manual (from an airflow point of view), only some are triggered by users and others are called by the background worker.
- Add a background worker
- Update cluster sync
Schedule pipelines, check if they are launched
=> Add a scheduler for airflow job

config/settings.py, config/urls.py, docker-compose.yaml
GraphQL is not optional / experimental anymore.
- Remove ENABLE_GRAPHQLsetting  from `config/settings.py`
- Remove ENABLE_GRAPHQL env variable from `docker-compose.yaml`
- Build a new image
- Test on localhosting
- Deploy in demo and prod
=> Remove ENABLE_GRAPHQL setting

hexa/plugins/connector_airflow/schema.py
Fix regression on resolve_dags: if the user doesnt have the perm to list all DAG, restrict the DAG list instead of crashing the backend over non existant index
- Go to index pipelines. if it doesnt crash as a non admin user, this fix works
=> Fix regression over user permission on dag list

config/settings.py, hexa/pipelines/authentication.py, hexa/pipelines/graphql/schema.graphql, hexa/pipelines/middlewares.py, hexa/pipelines/models.py, hexa/pipelines/schema.py
Add download pipeline-v2 code for the cloud runner. The pipeline run has no cookie, so no auhentication access; to make this work the backend needed a way to authenticate the pipelineRun: as in connector_airflow, it's done with a custom auth middleware.
- Add pipeline code download mutation
- Add pipeline run authentication
Run a pipeline in docker, whatch it download itself.
=> Add download mutation + run auth

hexa/pipelines/management/commands/pipelines_runner.py, requirements.in, requirements.txt
- The runner needs kubernetes lib, it was added to the requirements.in/txt
- The runner try to add pipeline pod in the default namespace, now using an env var
=> Fix pipeline runner: missing lib, default namespace

hexa/metrics/middlewares.py, hexa/pipelines/graphql/schema.graphql, hexa/pipelines/management/commands/pipelines_runner.py
- Fix KeyError for container name in pipelines-v2 runner
- Fix two factors authentication in API endpoint for pipeline runs
- Don't save the pipeline runs API calls because it doesn't have a valid user
=> Fix KeyError, two factor auth checking and metrics saving for pipelines-v2 runner

hexa/workspaces/permissions.py, hexa/workspaces/tests/test_models.py, hexa/workspaces/tests/test_schema.py
Allow any user with the `workspaces` feature flag to create a workspace - this will make testing easier.
- Replaced the check for superuser status in workspaces permissions by a check on the feature fag
If you have the workspace feature flag, you should be able to create a workspace.
=> Allow workspace creation if user has workspaces feature flag

hexa/data_collections/graphql/schema.graphql
OPENHEXA-M5
Reason: 
```
Fields 'id' conflict because they return conflicting types 'String!' and 'UUID!'. Use different aliases on the fields to fetch both if this was intentional.
GraphQL request:27:7
... on Collection {
id
^
name
GraphQL request:32:7
... on CatalogEntry {
id
^
name
```
=> fix(Search): adapt collection id to be a uuid instead of a string

hexa/workspaces/admin.py
Add entry in django admin for the Workspaces module
- Register Workspace model in django admin.
Connect to the admin page and check if the Workspaces module is present.
=> feat(Workspaces): add admin entry for workspaces

hexa/databases/api.py, hexa/databases/tests/test_api.py, hexa/databases/utils.py
A connection error may occur using credentials that contain special characters like "@,%". 
- Use keyword arguments for opening connection instead of URI string.
- Add function to return the database connection object.
Generate new credentials with special characters and check if the connection is established without error(s).
=> fix(Workspaces): fix psycopg2 connection error

hexa/databases/api.py, hexa/databases/tests/test_utils.py, hexa/databases/utils.py
Fix issue about workspace database tables not showing on demo. 
- Use workspace database credentials for introspection.
- Fix bugs that allowed created user to access to default  database data
=> fix(Workspaces): use Workspace DB credentials for instropection requests

hexa/plugins/connector_dhis2/admin.py
Fix error happening when searching for a dhis2 instance
- Replace display_name by name in search_fields
Go to the list of dhis2 instance on admin page and try search.
=> fix: replace display_name by name in search_fields for dhis2 admin

hexa/databases/api.py, hexa/databases/tests/test_api.py, hexa/workspaces/models.py, hexa/workspaces/tests/test_schema/test_workspace.py
Delete associated database when deleting a workspace.
- add method for deleting a database (the role and associated objects will be dropped)
- delete database when deleting workspace
Create/Use a workspace, go to settings page and click on delete. The workspace database should be deleted alongside the workspace
=> feat(Workspaces): delete database when deleting workspace

hexa/files/credentials.py, hexa/pipelines/views.py, hexa/workspaces/tests/test_views.py
We need this env variable, ideally for both notebooks and pipelines, in order to be able to generate absolute GCS URIs.
=> chore(Workspaces): add workspace bucket name env variable

hexa/pipelines/management/commands/pipelines_runner.py
The kube version of the pipelines runner was missing the HEXA_RUN_ID env variable.
=> fix(Pipelines): add missing HEXA_RUN_ID env var

hexa/core/tests/test_fixtures.py, hexa/user_management/fixtures/demo.json, hexa/user_management/migrations/0016_auto_20230330_1506.py, hexa/user_management/models.py
Add openhexa_legacy and workspaces feature flag to root user when installing fixtures.
- add features in fixtures
- use natural key in fixtures for user model 
Have a fresh install of openhexa-app and check if root user have access to legacy and workspaces part.
=> feat(User): add openhexa_legacy and workspaces features to root

hexa/pipelines/management/commands/pipelines_runner.py
Let's start without storing the optional termination message of the pipeline
=> chore: Remove termination message handling in pipelines runner

hexa/pipelines/management/commands/pipelines_runner.py
The goal is to configure the openhexa.sdk to be connected
See also: https://github.com/BLSQ/openhexa-sdk-python/pull/20
=> chore: Set the running environment of the SDK in the pipelines

hexa/plugins/connector_s3/api.py
This PR fixes `_get_app_s3_credentials` so that it uses the correct setting for the user ARN
=> fix(S3): fix assume role (wrong settings usage)

hexa/workspaces/models.py, hexa/workspaces/tests/test_schema/test_workspace.py
Fix broken update on workspace's member role update.
- Change filter_for_user query
- Ensure that a user cannot update/delete his own membership
- Test update of another user's role.
- Check if you can delete/update your own role
=> fix(Workspaces): fix workspace member role update

hexa/databases/tests/test_schema.py, hexa/pipelines/views.py, hexa/workspaces/models.py, hexa/workspaces/tests/test_views.py, hexa/workspaces/views.py
This PR simplifies how we generate workspaces database URL.
- Always use `db_url()` to generate the database URL
- Don't use `psycopg2` in the scheme
=> Fix(Databases): always use db_url

hexa/files/api.py, hexa/files/schema/mutations.py
When users wanted to download files, some triggered a the browser to download the object directly while other opened a new windows with the content of the file. 
We now ask to have a "download" content disposition set on the generated download url created by google.
=> fix(GCS): Add a content-disposition:download on object download url

hexa/workspaces/schema/types.py, hexa/workspaces/tests/test_schema/test_workspace_connection.py
When a user edited any field of a connection that had secret fields, those secret fields were reset to an empty value
We now return the value of the secret fields when the user is at least an member with the editor role
- Create a connection with at least 2 fields (one secret and one non secret).
- Edit the non secret field
- The secret field value should not have changed
=> fix(Connections): Returns the secret value for members that can edit them

hexa/workspaces/models.py, hexa/workspaces/tests/test_models.py
Before creating a connection from the slug provided by the API of the name, we check for the existence of a workspace connection with this slug In case we find one, we add a random suffix to the slug of the new connection.
=> fix(Connections): Add a suffix to connection slug if it exists

hexa/workspaces/graphql/schema.graphql, hexa/workspaces/models.py, hexa/workspaces/schema/mutations.py, hexa/workspaces/tests/test_schema/test_workspace.py
Makes optional demo data loaded when creating a workspace.
- update schema, mutation and model to handle to make demo data optional.
=> feat(Workspaces): set demo data optional

hexa/files/api.py, hexa/files/graphql/schema.graphql, hexa/files/schema/types.py, hexa/files/tests/mocks/backend.py, hexa/files/tests/mocks/blob.py, hexa/files/tests/mocks/bucket.py, hexa/files/tests/mocks/client.py, hexa/files/tests/test_api.py, hexa/files/tests/test_schema.py
- It adds a parameter on bucket.objects() to hide/display hidden objects (starting with ".").
- A client.list_blobs mock has been implemented as well
=> feat(Files): Show/hide hidden files & directories

hexa/files/api.py, hexa/files/tests/test_api.py
The pagination was broken when the user had a certain number of files in his buckets. It was displayed that no next page existed but it was a LIE.
The problem came from `current_page = next(page)` that was always called and could result in a `StopIteration` error.
I check in the loop if we have enough objects and break the loop early
=> fix(files): Break when we have enough objects (and before loading the next page)

hexa/pipelines/graphql/schema.graphql, hexa/pipelines/schema.py, hexa/pipelines/tests/test_schema.py
In pipelines, users can call `current_run.add_file_output` & `current_run.add_database_output`. We transform those two types of output to their correct representation of `BucketObject` & `DatabaseTable`.
Example of return when querying a pipeline run
```json
{
"data": {
"workspace": {
"bucket": {
"objects": {
"hasNextPage": false,
"hasPreviousPage": false,
"items": [
{
"name": ".hidden_files",
"key": ".hidden_files/"
},
{
"name": "all",
"key": "all/"
},
{
"name": "README.MD",
"key": "README.MD"
},
{
"name": "covid_data.csv",
"key": "covid_data.csv"
},
{
"name": "demo.ipynb",
"key": "demo.ipynb"
}
]
}
}
},
"pipelineRun": {
"id": "91efe9c7-277d-45e2-9d7a-3b9dbadf49fc",
"outputs": [
{
"__typename": "GenericOutput",
"name": "dhis2_extract.csv",
"uri": "httsp://google.com"
},
{
"__typename": …
```
=> Better pipeline outputs

hexa/workspaces/schema/mutations.py, hexa/workspaces/tests/test_schema/test_workspace.py
If a legacy user was invited, the workspaces feature flag was not attached to the user and thus he cannot access the workspace anyway.
This case was handled when inviting external users
We check if the feature has to be activated for the user
=> fix(Workspaces): Add the 'workspaces' feature to legacy users invited in a workspace

hexa/workspaces/schema/types.py, hexa/workspaces/tests/test_schema/test_workspace.py
Fix bug that allowed user from one workspace to be able to see invitations for others workspaces.
- Add filter by workspace and Queryset result.
=> fix(Workspaces): filter invitations by user and workspace

hexa/pipelines/management/commands/pipelines_runner.py, hexa/pipelines/tests/test_utils.py, hexa/pipelines/utils.py
Fix for issue about[ pipeline pod names](https://github.com/BLSQ/openhexa-team/issues/530).
- Append random string to pipeline pod name.
=> fix(Pipelines): generate random string to avoid pod names collision

hexa/datasets/graphql/schema.graphql, hexa/datasets/schema/mutations.py, hexa/datasets/tests/test_schema.py
- Users can now get files by name from the version
- Only the latest version of a dataset accepts new uploads of files
=> feat(Datasets): add fileByName on dataset's version, datasets improvements

hexa/databases/tests/test_utils.py, hexa/databases/utils.py
`get_table_rows` always removed the last item of the items returned by the DB. In case we have the exact number of items, we should not remove the last one and just take the page size requested by the user instead.
=> fix(Databases): get_table_rows has to take the page_size from the db return

hexa/datasets/models.py, hexa/datasets/tests/test_models.py, hexa/workspaces/models.py
This is to prevent the creation of slugs like `my-dataset--za21`
=> fix: Do not allow slugs for workspace, datasets & connection to have double dash

hexa/workspaces/schema/mutations.py
The check is not needed anymore, as every membership should always have an access token. Moreover, the `generate_access_token` method does not exist anymore.
=> Fix(Workspaces): don't test for access tokens in resolve_generate_workspace_token

README.md
When working on BLSQ/openhexa-team#565, I've found a few incorrect, incomplete, or misleading instructions.
The present changes bring a few minor quick corrections to those.
There are other changes to address those issues, but they'll require more work (e.g. fix the permission issue with test coverage reports). This is out of the current scope.
- `README.md` :
- The used Docker Compose command is deprecated
- The host URL to access the app isn't mentioned
- The way to get the test coverage report is incomplete, it requires to be in the container, also the issue with permission is not mentioned
- It is not explained how you could run a single test
=> Fix a wrong or incomplete instructions in README

README.md
While testing the doc for onboarding, a few unclear parts have been spot
See BLSQ/openhexa-team#565
* confusing instruction about standalone Docker image
* how to change the code
* missing details about the test harness tool
* missing served endpoints.
=> Improve some part of the README

README.md
The current README.md contains a lot of outdated information, especially about "What is OpenHexa".
We have a wiki for that, so let's simplify the README and refer to the wiki for everything else.
=> doc: Simplify README.md

config/settings.py
We no longer use openhexa-pipelines
=> fix: Use blsq/openhexa-base-notebook:latest by default for pipelines

hexa/datasets/schema/mutations.py, hexa/datasets/tests/test_schema.py, hexa/datasets/tests/testutils.py, hexa/files/tests/mocks/blob.py, hexa/files/tests/mocks/bucket.py
Seems that we weren't using the proper check for the download dataset version file mutation.
- Fix permission check
- Add test
- Add missing pieces to the GCS mock setup
Download dataset files as a viewer.
=> fix: Fix permission check for dataset download

hexa/pipelines/management/commands/pipelines_runner.py
The run of pipelines in local with docker was not working properly.
- Use `cloudrun` argument instead of `run` in container launch cmd.
=> fix(Pipelines): run pipeline with cloudrun argument

hexa/plugins/connector_dhis2/templates/connector_dhis2/instance_detail.html, hexa/plugins/connector_postgresql/templates/connector_postgresql/datasource_detail.html, hexa/plugins/connector_s3/templates/connector_s3/bucket_detail.html
Step 1 : remove datasources elements views (e.g : org_unit, indicator)
- Remove datasources views (only keeping datasource card for now) and details.
- Delete connector_iaso folder.
=> chore(Catalog): deprecate datasources views

README.md, config/settings.py, docker-entrypoint.sh
We recently removed django-tailwind from this component (we still have tailwind classes and a CSS file generated using django-tailwind but it has been included as a static asset and won't change anymore).
This PR addresses a few leftovers.
- Removed django-tailwind commands from entrypoint
- Adapt documentation
Follow local setup instructions and make sure everything works.
=> fix: remove django-tailwind commands and adapt documentation

config/settings.py, docker-compose.yaml
When working with Docker (locally), the backend has to communicate with the JupyterHub API. Previously, it used the host URL as JupyterHub is exposed on its port 8001. It is not necessary to go through the host. The communication can be done to the Docker network dedicated to OpenHexa services.
Issue BLSQ/openhexa-team#617
=> Keep comm with JupyterHub API internal to the Docker network

config/settings.py, config/urls.py, docker-compose.yaml, hexa/notebooks/api.py, hexa/notebooks/tests/test_schema.py, hexa/user_management/tests/test_views.py, hexa/user_management/views.py
This PR simplifies logout by integrating the jupyterhub logout call in the logout view.
This allows us to logout through a simple POST request from the frontend (POST is required since Django 5) without any CORS issues caused by a redirection chain.
- Add a custom `LogoutView` that performs a `GET` logout request on Jupyterhub
- Replaced `NOTEBOOKS_API_URL` by `NOTEBOOKS_HUB_URL` (used both for API calls and logout)
- Login
- Logout (in legacy, in workspace menu, on account page...)
=> fix: logout handling for Django 5

hexa/pipelines/middlewares.py
It was possible until now to re-use a token of a pipeline after the run has been terminated.
.
=> fix(Auth): Only tokens from running pipelines can be used to authenticate the user

hexa/user_management/views.py
We call jupyterhub before logging out the user to also log him out of the hub.
=> fix(Notebooks): Logout the user from jupyterhub on logout

config/graphql/schema.graphql, hexa/files/graphql/schema.graphql
The size of workspace's objects can be bigger than an 32bit int.
=> Fix int overflow in the schema

hexa/pipelines/schema/types.py
We haven't seen this NotFound error in Sentry since the refactoring of Stephan. I added a catch for this exception in the outputs resolver to ignore it.
=> fix(Files): Do not log missing output files in Sentry

hexa/core/test/cases.py, hexa/datasets/schema/mutations.py, hexa/datasets/tests/test_schema.py
The pipeline is a specific type of user (unfortunately) and don't have the permission mechanic. Since we already get the file based on the workspace links, we are safe to only assert that the file is not None in case of a pipeline run user.
=> fix(datasets): Allow pipelines to download linked datasets

hexa/core/admin.py
The delete action on django admin for soft_deleted models was a soft delete, or we wanted to hard delete models from the admin. This PR override the default delete on the admin.
- Override delete_queryset to  hard_delete.
=> fix(SoftDelete): hard delete model on django admin

hexa/files/basefs.py, hexa/files/gcp.py, hexa/files/s3.py, hexa/files/tests/mocks/bucket.py, hexa/files/tests/mocks/client.py, hexa/files/tests/test_api.py, hexa/workspaces/models.py
The goal is to be able to easily know on the billing export on GCP which workspace consume what
=> chore(GCP): Set the workspace as a label on the bucket of the workspace

hexa/workspaces/graphql/schema.graphql, hexa/workspaces/schema/queries.py, hexa/workspaces/tests/test_schema/test_workspace_connection.py
Specify workspaceSlug to avoid multiple connections returned.
=> fix(Connections): specify connection workspace

hexa/datasets/schema/types.py
Last updated should match the date of the version upload, [see](https://bluesquare.atlassian.net/jira/software/c/projects/HEXA/boards/330?assignee=712020%3A1d0055ff-af59-47b7-b48d-4d37e2a0d0b9&selectedIssue=HEXA-995). 
- Return dataset last_version updated_at field if it exists.
=> fix(Datasets): use dataset last version to track update

hexa/files/gcp.py, hexa/files/s3.py
Having CORS on every buckets prevent customers to use work with signed urls in their frontend applications
=> fix(CORS): Allow objects to be uploaded & download from everywhere

docker-entrypoint.sh
The DB hostname was hardcoded as `db` in the entrypoint of the Docker image. That avoids us to change it for something else.
=> Make configurable the DB hostname in the container

hexa/analytics/api.py, hexa/analytics/tests/test_analytics.py
In the case of pipelines, the user of the request is an instance of `PipelineRunUser`. In this situation, we do not have the `analytics_enabled` flag on it
=> fix(analytics): PipelineRunUser should be excluded

hexa/analytics/urls.py, hexa/datasets/schema/mutations.py, hexa/pipelines/signals.py, hexa/workspaces/models.py
- The filtering clause set in the `filter_for_user` to handle the PipelineRunUser users was incorrect.
- Analytics endpoint should end with a trailing slash
=> Fix pipeline run user perms

hexa/analytics/api.py, hexa/analytics/tests/test_analytics.py, hexa/datasets/schema/mutations.py, hexa/pipelines/management/commands/pipelines_scheduler.py, hexa/pipelines/schema/mutations.py, hexa/pipelines/views.py
Track more meaningful properties for pipeline_run event.
- use pipeline_code instead of pipeline_id
=> fix(Analytics): use pipeline code for id

docker-compose.yaml, hexa/core/views_utils.py, hexa/pipelines/signals.py, hexa/pipelines/views.py
The signal that I added prevent the frontend to load the static assets of the admin. By changing the implementation, I've fixed the static problem and kept the deactivation of the cors on the `run_pipeline` endpoint
=> Remove cors decorator

config/settings/base.py
When setting `TRUST_FORWARDED_PROTO` to `no`, it was anyway interpreted as a `yes` as we were only checking for its presence. That led to a misconfiguration of the cookie and csrf avoiding login.
=> Fix wrong mgt of env var TRUST_FORWARDED_PROTO

hexa/databases/api.py
Starting from PostgreSQL 15+, we need to grant all access to the public schema to the role when creating a database
No changes are needed for existing databases, the default behavior is kept
More info on https://www.postgresql.org/docs/release/15.0/
=> fix(DB): Starting from PostgreSQL 15+ it's needed to grant all on the public schema to allow creation and deletion of tables by the user

hexa/files/backends/dummy.py, hexa/pipelines/schema/types.py, hexa/pipelines/tests/test_schema/test_pipelines.py
The changes for the new storage backend had an impact on the PipelineRun outputs.
=> fix(Pipelines): Run outputs can be a StorageObject instance

.github/workflows/test.yml, Dockerfile
The previous image set root as the default user. This means that a process has the root rights and can create files with this id in a mounted volume from the host. This is a common attack vector.
With the present change, the container will run under a normal user `openhexa` without any root permission.
Noticed that doesn't make Docker rootless. This requires to prepare the Docker engine to run in a normal userspace. This goes beyond the present change.
run the whole app and test it
=> Make the Docker image "rootless"

hexa/datasets/schema/mutations.py
Small fix : forgot to migrate to snake case the linkId used in pinDataset mutation.
- Use snake case for link id.
Call the pinDataset mutation with correct input, it shouldn't break.
=> fix(Datasets): snake case for datasetlink id

hexa/pipelines/graphql/schema.graphql, hexa/pipelines/schema/types.py
Fixes OPENHEXA-1BT
I added the `number` field again on `PipelineVersion`
Try uploading & downloading pipelines using a version of openhexa.sdk < 1.0.0
=> fix(Pipelines): Put back 'number' on PipelineVersion to not break backward compatibility with SDK < 1.0.0

hexa/analytics/api.py
By default it waited a timeout on the mixpanel side and retried all requests 4 times.
Fixes OPENHEXA-1CH & OPENHEXA-1BM
=> Mixpanel: Prevent our integration to block our backend

hexa/pipeline_templates/fixtures/base.json
It's better to use the fixture mechanism of Django to manage feature flags.
=> chore(Templates): Add missing fixture to create the feature flag

requirements.in, requirements.txt
I upgraded Django to the latest version available.
https://docs.djangoproject.com/en/5.1/releases/5.0/
=> chore(deps): Upgrade Django from v4 to v5

hexa/pipeline_templates/schema/mutations.py
Support deleted source pipeline
This change should have no effect now because this method is only used when creating a new template or template version, but this is only proposed when the source pipeline is not deleted. So at this point it is for correctness or avoiding future issues.
=> fix: Support deleted source pipeline (HEXA-1169)

hexa/datasets/graphql/schema.graphql, hexa/datasets/models.py, hexa/datasets/schema/mutations.py, hexa/datasets/tests/test_models.py, hexa/datasets/tests/test_schema.py
Fixes PATHWAYS-308 for the backend
Add a way for admin & editors to edit the name & changelog of dataset versions of their workspaces
Call the mutation 'updateDatasetVersion' via GraphiQL or wait for the frontend to be available
=> chore(Datasets): Add a updateDatasetVersion mutation

.github/workflows/release-please.yml, README.md
Until now it was a manual task to release a hot fix on the previous version.
This PR addresses that by running release-please on release/* branches. The rest stays the same.
=> Release please on release branches

hexa/superset/admin.py, hexa/superset/models.py, hexa/superset/urls.py, hexa/superset/views.py
- "View on site" link in the Django admin redirects to the embedded dashboard on app.openhexa.org and not api.openhexa.org (it's now using `NEW_FRONTEND_DOMAIN`)
- Add inline panel to add dashboards directly from the admin page of a superset instance
- Add temporary endpoint to support getting dashboard by their external id (this is what's used by the former system)
- Click on "view on site", you should arrive on http://localhost:3000
- Test the endpoint `/superset/dashboard/external/<external_id>`
=> Superset improvements

hexa/user_management/schema.py, hexa/user_management/tests/test_schema.py
Password reset email was like :
```
Please go to the following page and choose a new password:
http://https://app.openhexa.org/auth/reset/ODFhOTRlY2MtNTI5Zi00N2ZjLThi
```
- Ensure the domain and protocol are correct and not doubled
- Cover with unit test
=> fix: Malformed URL for password reset (HEXA-1222)

frontend/next-env.d.ts, frontend/src/pages/workspaces/[workspaceSlug]/webapps/[webappId]/play/index.tsx, frontend/src/pages/workspaces/[workspaceSlug]/webapps/create/index.tsx, frontend/src/pages/workspaces/[workspaceSlug]/webapps/index.tsx, frontend/src/webapps/features/FavoriteWebappButton/FavoriteWebappButton.generated.tsx, frontend/src/webapps/features/FavoriteWebappButton/FavoriteWebappButton.tsx, frontend/src/webapps/features/FavoriteWebappButton/index.ts, frontend/src/webapps/features/WebappCard/WebappCard.generated.tsx, frontend/src/webapps/features/WebappCard/WebappCard.tsx, frontend/src/webapps/features/WebappCard/index.ts, frontend/src/webapps/features/WebappForm/WebappForm.tsx, frontend/src/webapps/features/WebappIframe/WebappIframe.test.tsx, frontend/src/webapps/features/WebappIframe/WebappIframe.tsx, frontend/src/webapps/features/WebappIframe/index.tsx, frontend/src/webapps/tests/WebappsPage.test.tsx, frontend/src/workspaces/features/DeleteConnectionTrigger/DeleteConnectionTrigger.test.tsx, frontend/src/workspaces/graphql/queries.generated.tsx, frontend/src/workspaces/graphql/queries.graphql
Improve Web apps UI base don Mariano's feedback after testing
- Update GraphQL schema according to latest backend version in https://github.com/BLSQ/openhexa-app/pull/959
- Add missing `await WorkspaceLayout.prefetch(ctx, client);` to avoid SRR issues
- Add a list of favorites
- Add a play button in the web apps grid
- `FavoriteWebappButton` based on Datasets example
- `WebappCard` to show favorites
- Encapsulate `iframe` logic in `WebappIframe`
- Ensure the `iframe` has the correct permissive attributes with a uni test
=> feat: Improve Web apps UI : favorites handling, iframe permissions,... (PATHWAYS-414)

.gitignore, backend/hexa/superset/api.py, backend/hexa/superset/views.py, frontend/server/index.mjs
+ Add logging in Sentry to know which dashboards are still reached using the former url
=> Redirect the url already hosted on Vercel to the new one in Django.

frontend/src/core/components/Dialog/Dialog.tsx
After the upgrade to Tailwind > 4.1.4, the backdrop is overlapping the dialog content
=> fix: Tailwind upgrade to > 4.1.4 is breaking the backdrop of dialog (HEXA-1258)

frontend/src/core/features/SpotlightSearch/HighlightedLink.tsx, frontend/src/core/features/SpotlightSearch/mapper.ts, frontend/src/core/features/SpotlightSearch/useSearchHotkeys.tsx
Templates are objects that can be shared across workspaces. If a user has no access to the workspace were the template was created, the link directing to the template page will not work. We can use the current workspace instead since the user has access to it
=> fix : search bar, navigating to templates can fail because the user is not member of the workspace (HEXA-1261) 

frontend/src/pages/workspaces/[workspaceSlug]/datasets/[datasetSlug]/index.tsx
We want to be able to edit the name of the last version of a dataset
=> fix: The name of the latest version of a dataset cannot be edited (HEXA-1257)

frontend/src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/index.tsx
Prevent the web hook toggle to be edited if not in edit mode. And also ensure that the checked value is always defined (it caused errors in the console)
=> fix: web hook toggle can be changed while not in edit mode (HEXA-1264)

backend/hexa/superset/apps.py
The default route was accessible without authentication but not the one used to replace the former system on Vercel.
=> Add missing superset route to the anonymous routes

frontend/src/pages/workspaces/[workspaceSlug]/pipelines/index.tsx, frontend/src/pipelines/features/Pipelines/Pipelines.generated.tsx, frontend/src/pipelines/features/Pipelines/Pipelines.tsx, frontend/src/workspaces/graphql/queries.generated.tsx, frontend/src/workspaces/graphql/queries.graphql
Loading the pipelines page was causing unneeded data fetching since the data was in the apollo cache
- Ensure the pipelines are queried during SRR
- Pass down the variables used for the query to the Pipelines component
- Leverage `useWorkspacePipelinesPageQuery` instead of defining a GraphQL query inline
=> fix: Caching and SRR of pipelines (HEXA-1262)

frontend/src/pipelines/features/Pipelines/GridView.tsx
User liked the last run badge seen in the search bar results and card view, bring it to the grid view
=> feat: add last run status to pipeline grid view (HEXA-1268)

backend/hexa/analytics/api.py, backend/hexa/user_management/graphql/schema.graphql, backend/hexa/user_management/models.py, backend/hexa/user_management/schema.py, backend/hexa/user_management/tests/test_schema.py, frontend/schema.generated.graphql, frontend/src/graphql/types.ts, frontend/src/identity/graphql/queries.generated.tsx, frontend/src/identity/graphql/queries.graphql, frontend/src/identity/hooks/__tests__/useFeature.test.tsx, frontend/src/identity/hooks/useFeature.ts
Globally enabled features were not sent to the frontend via `me.features`.
The new implementation returns all the features flags (global & user enabled).
The FeatureFlag.config has been removed from the API as it has never been used. 
- Test with a feature with `force_activate = True`. It should be returned as a feature flag of the user
=> chore: Expose globally enabled feature flags to users via GraphQL & remove FeatureFlag.config from GraphQL (not used)

backend/hexa/datasets/queue.py, backend/hexa/datasets/tests/test_generate_sample.py
We have errors coming up when infinity is used in column numbers. But it's not supported well by postgresql and our statistics methods
- Replace infinity by the equivalent string for sampling
- Replace infinity by 0 for profiling
- Update the profiling unit test
=> fix: profiling and sampling issue with infinity (HEXA-1278)

frontend/src/core/components/forms/Input/Input.tsx, frontend/src/core/features/SearchInput.tsx, frontend/src/core/hooks/useDebounce.ts, frontend/src/pipelines/features/Pipelines/GridView.tsx, frontend/src/pipelines/features/Pipelines/Pipelines.tsx
We receive a [sentry alert ](https://bluesquareorg.sentry.io/issues/6635357862/?alert_rule_id=7767430&alert_type=issue&notification_uuid=30177688-c53d-40a9-91a9-280093fd7dc0&project=5893042&referrer=slack) because when changing page of results while searching for pipelines and then searching again, the page is not reset to 1.
- Reset the page to 1 after the debounce when the query is changing
- Fix a UI glitch caused by z-indexes
=> fix: searching when changing page of results & UI glitch caused by z-index (HEXA-1293)

backend/hexa/core/utils.py, backend/hexa/pipelines/utils.py, backend/hexa/user_management/utils.py, backend/hexa/workspaces/utils.py
Attachments were missing in the `send_email` call
- Add the missing `.svg` attachment
- Extract into utils a helper method to include the `.png` logo, to be reused across the apps.
=> fix:  images in emails are not shown correctly, at least in gmail (HEXA-1351)

backend/hexa/datasets/admin.py, backend/hexa/pipelines/admin.py, backend/hexa/user_management/admin.py, backend/hexa/workspaces/admin.py
Investigating stuff is difficult, with pages timing out (pipeline runs) and massive user/workspace-select lists.
Example autocomplete box:
=> chore: Make the Django admin a bit more userfriendly

frontend/src/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].tsx
I see in GCP 
```
textPayload: "TypeError: Cannot read properties of undefined (reading 'slug')
at <unknown> (.next/server/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].js:41:13628)
at children (.next/server/pages/workspaces/[workspaceSlug]/pipelines/[pipelineCode]/runs/[runId].js:41:15312)
at e (.next/server/chunks/2004.js:1:12298)"
```
But can not reproduce locally, however it's cleaner to take the workspace slug from the props directly, so testing this
=> fix: Viewing certain succeeded pipeline runs result in 500 errors (HEXA-1368)

backend/hexa/user_management/fixtures/base.json, backend/hexa/user_management/permissions.py, frontend/package-lock.json
Right now, only org admins can create workspace
We want to allow some users to bypass this check to unblock them while we find a more granular system
=> feat: feature flag for workspace creation

backend/hexa/user_management/utils.py
Fix https://bluesquareorg.sentry.io/issues/6822493320/?alert_rule_id=7767430&alert_type=issue&notification_uuid=59beafb9-e367-453d-900c-f6f14babad06&project=5893042&referrer=slack
The other tracking events of organization action are tracking the name and not the id, so we can take this opportunity to also use the name and solve the type issue
=> fix: Object of type UUID is not JSON serializable for mixpanel events on organization emails

backend/docker-entrypoint.sh
The default setting of password `root` presents a risk for local setups. The easy fix is to not set a default password and instead request the user's input.
Example run where I set pw `root`:
See also: https://github.com/BLSQ/openhexa-app/pull/1396
=> chore: Change `prepare` command to ask for superuser password
